"""Tests for ShipSafe Web Dashboard and REST API.

Verifies:
1. Dashboard loads HTML successfully
2. Overview endpoint returns real metrics
3. Agents endpoint returns 5 Bob agents
4. Requirements endpoint returns 5 requirements
5. Findings endpoint returns synthesized findings and supports filtering
6. Traceability endpoint returns full matrix
7. Simulation endpoint returns components and regression paths
8. Remediation endpoint returns prioritized items
9. Comparison endpoint returns baseline, bad release, and NOT_AVAILABLE post-remediation
10. Missing report produces explicit 404 error
11. Invalid JSON produces explicit error
"""

from __future__ import annotations

import json
import pytest
from pathlib import Path
from unittest.mock import patch

from shipsafe.web.app import create_app, DataStore


@pytest.fixture
def client():
    """Create a Flask test client for the default workspace app."""
    app = create_app()
    app.config["TESTING"] = True
    with app.test_client() as test_client:
        yield test_client


# ---------------------------------------------------------------------------
# 1. Dashboard loads
# ---------------------------------------------------------------------------

def test_dashboard_loads(client):
    """Verify that GET / returns HTTP 200 and contains core branding and release status."""
    res = client.get("/")
    assert res.status_code == 200
    html = res.get_data(as_text=True)
    assert "SHIPSAFE AI" in html
    assert "Agentic Release &amp; Regression Guardian" in html or "Agentic Release & Regression Guardian" in html
    assert "RELEASE BLOCKED" in html or "RELEASE READY" in html
    assert "IBM Bob 2.0 Analysis Agents" in html
    assert "REQUIREMENT TRACEABILITY" in html
    assert "WHAT HAPPENS IF I SHIP THIS?" in html
    assert "RELEASE MEASUREMENT" in html
    assert "PRIORITIZED REMEDIATION PLAN" in html


# ---------------------------------------------------------------------------
# 2. Overview endpoint returns real data
# ---------------------------------------------------------------------------

def test_overview_endpoint_returns_real_data(client):
    """Verify GET /api/overview returns release status and synthesized KPI counts."""
    res = client.get("/api/overview")
    assert res.status_code == 200
    data = res.get_json()
    assert data["status"] in ("RELEASE_BLOCKED", "RELEASE_READY")
    assert data["kpis"]["requirements_total"] == 5
    if data["status"] == "RELEASE_BLOCKED":
        assert data["kpis"]["total_findings"] == 22
        assert data["kpis"]["critical_count"] == 1
        assert data["kpis"]["high_count"] == 19
        assert data["kpis"]["requirements_failed"] == 5
    else:
        assert data["kpis"]["total_findings"] == 0
        assert data["kpis"]["critical_count"] == 0
        assert data["kpis"]["requirements_failed"] == 0
    assert "IBM Bob" in data["evidence_statement"]


# ---------------------------------------------------------------------------
# 3. Agent endpoint returns five Bob agents
# ---------------------------------------------------------------------------

def test_agent_endpoint_returns_five_bob_agents(client):
    """Verify GET /api/agents returns exactly five agents with IBM Bob attribution."""
    res = client.get("/api/agents")
    assert res.status_code == 200
    data = res.get_json()
    assert data["count"] == 5
    assert data["orchestrated_by"] == "IBM Bob 2.0"

    agent_ids = {a["agent_id"] for a in data["agents"]}
    expected_ids = {"impact", "test_gap", "security", "contract", "database"}
    assert agent_ids == expected_ids

    # Each agent must have valid status and findings
    for a in data["agents"]:
        assert a["status"] in ("COMPLETE", "RELEASE_BLOCKED")
        assert a["finding_count"] > 0
        assert "Historical analysis artifact generated by IBM Bob 2.0" in a["attribution"]


# ---------------------------------------------------------------------------
# 4. Requirements endpoint returns five requirements
# ---------------------------------------------------------------------------

def test_requirements_endpoint_returns_five_requirements(client):
    """Verify GET /api/requirements returns R001 through R005 with compliance data."""
    res = client.get("/api/requirements")
    assert res.status_code == 200
    data = res.get_json()
    assert data["count"] == 5
    req_ids = [r["requirement_id"] for r in data["requirements"]]
    assert req_ids == ["R001", "R002", "R003", "R004", "R005"]


# ---------------------------------------------------------------------------
# 5. Findings endpoint returns synthesized findings
# ---------------------------------------------------------------------------

def test_findings_endpoint_returns_synthesized_findings(client):
    """Verify GET /api/findings returns findings and supports severity filtering."""
    res = client.get("/api/findings")
    assert res.status_code == 200
    data = res.get_json()
    assert data["total_available"] in (0, 22)
    assert data["filtered_count"] in (0, 22)

    # Filter for critical findings only
    res_crit = client.get("/api/findings?severity=CRITICAL")
    assert res_crit.status_code == 200
    data_crit = res_crit.get_json()
    if data["total_available"] == 22:
        assert data_crit["filtered_count"] == 1
        assert data_crit["findings"][0]["severity"] == "CRITICAL"
    else:
        assert data_crit["filtered_count"] == 0

    # Filter for high findings only
    res_high = client.get("/api/findings?severity=HIGH")
    assert res_high.status_code == 200
    data_high = res_high.get_json()
    if data["total_available"] == 22:
        assert data_high["filtered_count"] == 19
    else:
        assert data_high["filtered_count"] == 0


# ---------------------------------------------------------------------------
# 6. Traceability endpoint works
# ---------------------------------------------------------------------------

def test_traceability_endpoint_works(client):
    """Verify GET /api/traceability returns matrix and includes R003 details."""
    res = client.get("/api/traceability")
    assert res.status_code == 200
    data = res.get_json()
    assert "requirements" in data
    r003 = next(r for r in data["requirements"] if r["requirement_id"] == "R003")
    assert r003["validation"]["state"] in ("CONFLICTED", "VALIDATED")
    if r003["validation"]["state"] == "CONFLICTED":
        assert "conflicts" in r003
        assert len(r003["conflicts"]) > 0


# ---------------------------------------------------------------------------
# 7. Simulation endpoint works
# ---------------------------------------------------------------------------

def test_simulation_endpoint_works(client):
    """Verify GET /api/simulation returns components, workflows, and regression paths."""
    res = client.get("/api/simulation")
    assert res.status_code == 200
    data = res.get_json()
    assert "affected_components" in data
    assert "regression_paths" in data
    assert "highest_risk_component" in data
    if data.get("release_status") == "RELEASE_BLOCKED":
        assert len(data["affected_components"]) > 0
        assert len(data["regression_paths"]) > 0
    else:
        assert len(data["affected_components"]) == 0
        assert len(data["regression_paths"]) == 0


# ---------------------------------------------------------------------------
# 8. Remediation endpoint works
# ---------------------------------------------------------------------------

def test_remediation_endpoint_works(client):
    """Verify GET /api/remediation returns ordered remediation items starting with P1 (R004)."""
    res = client.get("/api/remediation")
    assert res.status_code == 200
    data = res.get_json()
    assert "remediation_items" in data
    items = data["remediation_items"]
    assert len(items) == 5
    # P1 must be R004 (critical SQL injection)
    assert items[0]["priority"] == "CRITICAL"
    assert items[0]["requirement_id"] == "R004"


# ---------------------------------------------------------------------------
# 9. Comparison endpoint works
# ---------------------------------------------------------------------------

def test_comparison_endpoint_works(client):
    """Verify GET /api/comparison returns baseline, bad release, and post-remediation data."""
    res = client.get("/api/comparison")
    assert res.status_code == 200
    data = res.get_json()
    assert "baseline" in data
    assert "bad_release" in data
    assert "post_remediation" in data
    assert data["baseline"]["tests"]["passed"] == 38
    assert data["bad_release"]["tests"]["passed"] == 31
    post_status = data["post_remediation"].get("state") or data["post_remediation"].get("status")
    assert post_status in ("NOT_AVAILABLE", "RELEASE_READY", "MEASURED", "POST_REMEDIATION")
    if post_status != "NOT_AVAILABLE":
        assert data["post_remediation"]["tests"]["passed"] >= 38


# ---------------------------------------------------------------------------
# 10. Missing report produces explicit error
# ---------------------------------------------------------------------------

def test_missing_report_produces_explicit_error(client):
    """Verify querying an invalid or non-existent report returns 404 with structured error."""
    # API route
    res = client.get("/api/report/non_existent_key")
    assert res.status_code == 404
    data = res.get_json()
    assert data["status"] == "NOT_FOUND"
    assert "Unknown report key" in data["error"]

    # Web UI route
    res_web = client.get("/report/unknown_report_xyz")
    assert res_web.status_code == 404


# ---------------------------------------------------------------------------
# 11. Invalid JSON produces explicit error
# ---------------------------------------------------------------------------

def test_invalid_json_produces_explicit_error(tmp_path: Path):
    """Verify that corrupted JSON in a report artifact produces a clear 500 error."""
    # Create a corrupted report in temporary directory
    bad_file = tmp_path / "reports" / "latest_release_report.json"
    bad_file.parent.mkdir(parents=True, exist_ok=True)
    bad_file.write_text("{corrupted json content: true", encoding="utf-8")

    app = create_app(repo_root=tmp_path)
    app.config["TESTING"] = True
    test_client = app.test_client()

    res = test_client.get("/api/report/synthesis")
    assert res.status_code == 500
    data = res.get_json()
    assert data["status"] == "INVALID_JSON"
    assert "Invalid JSON in report" in data["error"]


# ---------------------------------------------------------------------------
# 12. Report detail page loads
# ---------------------------------------------------------------------------

def test_report_detail_page_loads(client):
    """Verify that /report/<type> renders readable HTML for various reports."""
    for report_key in ["synthesis", "traceability", "simulation", "agent-security"]:
        res = client.get(f"/report/{report_key}")
        assert res.status_code == 200
        html = res.get_data(as_text=True)
        assert "Audit Trail / Report Viewer" in html
        assert "Back to Guardian Dashboard" in html


# ---------------------------------------------------------------------------
# 13. Refresh endpoint
# ---------------------------------------------------------------------------

def test_refresh_endpoint(client):
    """Verify POST /api/refresh reloads report cache from disk."""
    res = client.post("/api/refresh")
    assert res.status_code == 200
    data = res.get_json()
    assert data["status"] == "OK"
    assert "reloaded" in data["message"].lower()
